name: CD

on:
  push:
    branches:
      - main
  release:
    types: [published, created, edited]

jobs:
  call-ci:
    name: Call CI
    uses: Teyik0/auth-api-prisma-sample/.github/workflows/ci.yml@main

  deploy:
    needs: call-ci
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push when release
        uses: docker/build-push-action@v5
        if: ${{ github.event_name == 'release' && github.event.release.tag_name }}
        with:
          push: true
          tags: |
            teyik0/auth-api-sample:${{ github.event.release.tag_name }}

      - name: Build and push to production
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            teyik0/auth-api-sample:latest
